version: "3.8"

services:
  mongo1:
    image: mongo
    container_name: mongo1
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo1:27017'}]}) }" | mongosh --port 27017 --quiet
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - mongo1-data:/data/db
    # networks:
    #   - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo1
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo1

#   mongo2:
#     image: mongo
#     container_name: mongo2
#     command: ["mongod", "--replSet", "rs0"]
#     ports:
#       - "27018:27017"
#     volumes:
#       - mongo2-data:/data/db
#     networks:
#       - mongo-network

#   mongo3:
#     image: mongo
#     container_name: mongo3
#     command: ["mongod", "--replSet", "rs0"]
#     ports:
#       - "27019:27017"
#     volumes:
#       - mongo3-data:/data/db
#     networks:
#       - mongo-network

# networks:
#   mongo-network:
#     driver: bridge

volumes:
  mongo1-data:
  # mongo2-data:
  # mongo3-data:
