name: deploy
on:
  workflow_run:
    workflows: [test]
    branches: [main]
    types:
      - completed

# env:
#   PROJECT_ID: thinkspace-backend # TODO: update Google Cloud project id
#   GAR_LOCATION: asia-east2 # TODO: update Artifact Registry location
#   REPOSITORY: thinkspace-backend-repo # TODO: update Artifact Registry repository name
#   SERVICE: thinkspace-backend-service # TODO: update Cloud Run service name
#   REGION: asia-east2 # TODO: update Cloud Run service region

jobs:
  deploy:
    environment: production
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Docker Auth
        id: docker-auth
        uses: 'docker/login-action@v1'
        with:
          registry: ${{ vars.GAR_LOCATION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Build and Push Container
        run: |-
          docker build -t "${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ vars.SERVICE }}:${{ github.sha }}" ./
          docker push "${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ vars.SERVICE }}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ vars.SERVICE }}
          region: ${{ vars.REGION }}
          image: ${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ vars.SERVICE }}:${{ github.sha }}
          env_vars: |-
            JWT_ACCESS_TOKEN_SECRET=${{ secrets.JWT_ACCESS_TOKEN_SECRET }}
            JWT_REFRESH_TOKEN_SECRET=${{ secrets.JWT_REFRESH_TOKEN_SECRET }}
            MONGODB_URI=${{ secrets.MONGODB_URI }}
            EXPRESS_PORT=${{ vars.EXPRESS_PORT }}
            FRONTEND_SERVER=${{ vars.FRONTEND_SERVER }}
            JWT_ACCESS_EXPIRATION=${{ vars.JWT_ACCESS_EXPIRATION }}
            JWT_REFRESH_EXPIRATION=${{ vars.JWT_REFRESH_EXPIRATION }}
            S3_REGION=${{ vars.S3_REGION }}
            S3_BUCKETNAME=${{ vars.S3_BUCKETNAME }}
            S3_ACCESSKEYID=${{ secrets.S3_ACCESSKEYID }}
            S3_SECRETACCESSKEY=${{ secrets.S3_SECRETACCESSKEY }}
            DEFAULT_PROFILE_IMG=${{ vars.DEFAULT_PROFILE_IMG }}
            LOKI_HOST=${{vars.LOKI_HOST}}
          flags: '--port=8080 --allow-unauthenticated'

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
